'use client'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { getBrowserSupabase } from '@/lib/supabase'
import { useStore } from '@/lib/useStore'
import { rupiah } from '@/lib/utils'
export default function Products(){const {store}=useStore();const [rows,setRows]=useState<any[]>([]);const [q,setQ]=useState('');const [status,setStatus]=useState('all');const [page,setPage]=useState(1);const [size,setSize]=useState(10);const [loading,setLoading]=useState(true)
async function load(){if(!store)return;setLoading(true);const {data}=await getBrowserSupabase().from('products').select('*,categories(name)').eq('store_id',store.id).order('created_at',{ascending:false});setRows(data||[]);setLoading(false)}
useEffect(()=>{load()},[store]);const filtered=useMemo(()=>rows.filter(x=>(!q||x.name.toLowerCase().includes(q.toLowerCase()))&&(status==='all'||(status==='published'?x.is_published:!x.is_published))),[rows,q,status]);const totalPages=Math.max(1,Math.ceil(filtered.length/size));const shown=filtered.slice((page-1)*size,page*size)
async function toggle(id:string,value:boolean){await getBrowserSupabase().from('products').update({is_published:!value}).eq('id',id);load()}
async function remove(id:string){if(!confirm('Hapus produk ini?'))return;await getBrowserSupabase().from('products').delete().eq('id',id);load()}
return <div><div className="dashHeader"><div><span className="eyebrow">KATALOG</span><h1>Produk</h1><p>Kelola seluruh produk dan link affiliate toko.</p></div><Link className="btn primary" href="/dashboard/products/new">＋ Tambah Produk</Link></div>
<div className="panel"><div className="toolbar"><input placeholder="Cari produk..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Semua status</option><option value="published">Published</option><option value="draft">Draft</option></select><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option>10</option><option>25</option><option>50</option></select></div>
<div className="tableWrap"><table><thead><tr><th>Produk</th><th>Kategori</th><th>Harga</th><th>Status</th><th>Klik</th><th>Aksi</th></tr></thead><tbody>{shown.map(p=><tr key={p.id}><td><div className="productCell"><div className="tableThumb">{p.image_url?<img src={p.image_url} alt=""/>:'✦'}</div><div><b>{p.name}</b><small>{p.marketplace}</small></div></div></td><td>{p.categories?.name||'-'}</td><td>{rupiah(p.price)}</td><td><button className={p.is_published?'pill success':'pill'} onClick={()=>toggle(p.id,p.is_published)}>{p.is_published?'Published':'Draft'}</button></td><td>{p.click_count}</td><td><div className="actions"><Link href={`/dashboard/products/${p.id}`}>Edit</Link><button onClick={()=>remove(p.id)}>Hapus</button></div></td></tr>)}</tbody></table>{!loading&&!shown.length&&<div className="empty">Produk tidak ditemukan.</div>}</div>
<div className="pagination"><span>{filtered.length} produk</span><div><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>‹</button><span>{page} / {totalPages}</span><button disabled={page>=totalPages} onClick={()=>setPage(x=>x+1)}>›</button></div></div></div></div>}
