'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { getBrowserSupabase } from '@/lib/supabase'
import { useStore } from '@/lib/useStore'
import { slugify } from '@/lib/utils'
export default function ProductForm({id}:{id?:string}){const router=useRouter();const {store}=useStore();const [cats,setCats]=useState<any[]>([]);const [loading,setLoading]=useState(false);const [uploading,setUploading]=useState(false);const [form,setForm]=useState({name:'',category_id:'',description:'',image_url:'',video_url:'',price:'',compare_at_price:'',affiliate_url:'',marketplace:'Shopee',badge:'',is_featured:false,is_published:true})
useEffect(()=>{if(!store)return;const s=getBrowserSupabase();s.from('categories').select('*').eq('store_id',store.id).eq('is_active',true).order('sort_order').then(({data})=>setCats(data||[]));if(id)s.from('products').select('*').eq('id',id).single().then(({data})=>data&&setForm({name:data.name,category_id:data.category_id||'',description:data.description||'',image_url:data.image_url||'',video_url:data.video_url||'',price:String(data.price||''),compare_at_price:String(data.compare_at_price||''),affiliate_url:data.affiliate_url||'',marketplace:data.marketplace||'Shopee',badge:data.badge||'',is_featured:!!data.is_featured,is_published:!!data.is_published}))},[store,id])
function set(k:string,v:any){setForm(x=>({...x,[k]:v}))}
async function upload(file:File){if(!store)return;setUploading(true);try{const s=getBrowserSupabase();const ext=file.name.split('.').pop();const path=`${store.id}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await s.storage.from('product-images').upload(path,file,{upsert:false});if(error)throw error;const {data}=s.storage.from('product-images').getPublicUrl(path);set('image_url',data.publicUrl)}catch(e:any){alert(e.message)}finally{setUploading(false)}}
async function submit(e:React.FormEvent){e.preventDefault();if(!store)return;setLoading(true);const payload={store_id:store.id,category_id:form.category_id||null,name:form.name.trim(),slug:slugify(form.name)+'-'+Math.random().toString(36).slice(2,7),description:form.description||null,image_url:form.image_url||null,video_url:form.video_url||null,price:Number(form.price||0),compare_at_price:form.compare_at_price?Number(form.compare_at_price):null,affiliate_url:form.affiliate_url.trim(),marketplace:form.marketplace,badge:form.badge||null,is_featured:form.is_featured,is_published:form.is_published};const s=getBrowserSupabase();let error:any=null;if(id){const {slug,...updatePayload}=payload;const result=await s.from('products').update(updatePayload).eq('id',id);error=result.error}else{const result=await s.from('products').insert(payload);error=result.error}setLoading(false);if(error)return alert(error.message);router.push('/dashboard/products')}
return <form className="formPanel" onSubmit={submit}><div className="formGrid"><section className="panel"><h2>Informasi Produk</h2><label>Nama Produk<input value={form.name} onChange={e=>set('name',e.target.value)} required placeholder="Contoh: Smartwatch AMOLED Series 9"/></label><div className="formRow"><label>Kategori<select value={form.category_id} onChange={e=>set('category_id',e.target.value)}><option value="">Tanpa kategori</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Marketplace<select value={form.marketplace} onChange={e=>set('marketplace',e.target.value)}><option>Shopee</option><option>TikTok Shop</option><option>Tokopedia</option><option>Lazada</option><option>Lainnya</option></select></label></div><label>Deskripsi<textarea rows={6} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Jelaskan alasan produk ini direkomendasikan..."/></label><div className="formRow"><label>Harga<input type="number" min="0" value={form.price} onChange={e=>set('price',e.target.value)} required/></label><label>Harga Coret<input type="number" min="0" value={form.compare_at_price} onChange={e=>set('compare_at_price',e.target.value)}/></label></div><label>Link Affiliate<input type="url" value={form.affiliate_url} onChange={e=>set('affiliate_url',e.target.value)} required placeholder="https://s.shopee.co.id/..."/><small>Gunakan link affiliate yang sudah dibuat dari marketplace.</small></label></section>
<aside><section className="panel"><h2>Media Produk</h2><div className="uploadBox">{form.image_url?<img src={form.image_url} alt="preview"/>:<span>▧</span>}<label className="btn ghost">{uploading?'Uploading...':'Upload Foto Utama'}<input hidden type="file" accept="image/*" disabled={uploading} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label><small>atau tempel URL gambar</small><input value={form.image_url} onChange={e=>set('image_url',e.target.value)} placeholder="https://.../foto-produk.jpg"/></div><label className="videoUrlField">Video URL<input type="url" value={form.video_url} onChange={e=>set('video_url',e.target.value)} placeholder="https://.../video.mp4 atau YouTube"/><small>Bisa URL video MP4/WebM langsung atau YouTube. URL video marketplace tetap disimpan; bila tidak mendukung embed akan tersedia tombol buka video.</small></label></section><section className="panel"><h2>Publikasi</h2><label>Badge<input value={form.badge} onChange={e=>set('badge',e.target.value)} placeholder="Best Seller / Viral / Diskon"/></label><label className="check"><input type="checkbox" checked={form.is_featured} onChange={e=>set('is_featured',e.target.checked)}/> Produk unggulan</label><label className="check"><input type="checkbox" checked={form.is_published} onChange={e=>set('is_published',e.target.checked)}/> Publish sekarang</label></section></aside></div><div className="formActions"><button type="button" className="btn ghost" onClick={()=>router.back()}>Batal</button><button className="btn primary" disabled={loading}>{loading?'Menyimpan...':'Simpan Produk'}</button></div></form>}
