import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { getServerSupabase } from '@/lib/supabase'
import { rupiah } from '@/lib/utils'
import ViewTracker from '@/components/ViewTracker'
import ProductMedia from '@/components/ProductMedia'
export const dynamic='force-dynamic'
async function getData(productSlug:string){const s=getServerSupabase();if(!s)return null;const {data:store}=await s.from('stores').select('*').eq('is_active',true).order('created_at',{ascending:true}).limit(1).maybeSingle();if(!store)return null;const {data:product}=await s.from('products').select('*,categories(name,slug)').eq('store_id',store.id).eq('slug',productSlug).eq('is_published',true).single();return product?{store,product}:null}
export async function generateMetadata({params}:{params:Promise<{productSlug:string}>}):Promise<Metadata>{const p=await params;const d=await getData(p.productSlug);if(!d)return{title:'Produk tidak ditemukan | AffiOne'};return{title:`${d.product.name} | ${d.store.name}`,description:d.product.short_description||d.product.description||`Cek ${d.product.name}`,openGraph:{images:d.product.image_url?[d.product.image_url]:undefined}}}
export default async function ProductPage({params}:{params:Promise<{productSlug:string}>}){const p=await params;const d=await getData(p.productSlug);if(!d)notFound();const {store,product}=d;const discount=product.compare_at_price&&product.compare_at_price>product.price?Math.round((1-product.price/product.compare_at_price)*100):0;const highlights=(product.highlights||[]).filter(Boolean);const jsonLd={"@context":"https://schema.org","@type":"Product",name:product.name,image:[product.image_url,...(product.gallery_urls||[])].filter(Boolean),description:product.short_description||product.description||undefined,aggregateRating:{"@type":"AggregateRating",ratingValue:Number(product.rating||4.8),reviewCount:Math.max(1,Number(product.sold_count||1))},offers:{"@type":"Offer",priceCurrency:'IDR',price:product.price,url:product.affiliate_url,availability:'https://schema.org/InStock'}};return <main className="shopShell detailShell" style={{'--accent':store.accent_color} as React.CSSProperties}><ViewTracker productId={product.id}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header className="shopHeader detailHeader"><Link href="/" className="shopLogo">{store.logo_url?<img src={store.logo_url} alt={store.name}/>:<span>🛍</span>}<div><b>{store.name}</b><small>Affiliate Store</small></div></Link><nav><Link href="/">Beranda</Link><Link href="/#produk">Produk</Link><Link href="/#kategori">Kategori</Link></nav></header><div className="breadcrumbs"><Link href="/">Beranda</Link><span>›</span><span>{product.categories?.name||product.marketplace}</span><span>›</span><b>{product.name}</b></div><section className="marketDetail"><ProductMedia imageUrl={product.image_url} galleryUrls={product.gallery_urls} videoUrl={product.video_url} name={product.name}/><div className="detailCommerceInfo">{product.badge&&<span className="mallBadge">{product.badge}</span>}<h1>{product.name}</h1><div className="detailRating">★ {Number(product.rating||4.8).toFixed(1)} <span>· {(product.sold_count||0).toLocaleString('id-ID')}+ terjual</span></div><div className="detailPrice"><b>{rupiah(product.price)}</b>{product.compare_at_price&&<del>{rupiah(product.compare_at_price)}</del>}{discount>0&&<em>-{discount}%</em>}</div><a className="detailCta" href={`/api/track-click?product=${product.id}`} rel="nofollow sponsored">▣ Beli Sekarang di {product.marketplace} →</a><div className="trustList">{highlights.length?highlights.map((h:string)=><span key={h}>✓ {h}</span>):<><span>✓ Produk pilihan</span><span>✓ Checkout aman di marketplace</span><span>✓ Link langsung ke produk</span></>}</div></div></section><section className="productDescription"><div className="tabs"><b>Deskripsi</b><span>Informasi Produk</span></div><p>{product.description||product.short_description||'Belum ada deskripsi produk.'}</p></section><footer className="aboutStrip"><div><b>{store.name}</b><p>{store.tagline}</p></div><small>AffiOne</small></footer></main>}
