'use client'
import { useEffect,useMemo,useState } from 'react'
import { useStore } from '@/lib/useStore'
import { getBrowserSupabase } from '@/lib/supabase'
import { slugify } from '@/lib/utils'

const DEFAULT_ICONS=[
  ['bag','🛍️'],['electronics','💻'],['fashion','👕'],['beauty','💄'],['home','🏠'],['baby','🍼'],['sport','⚽'],['auto','🚗'],['food','🍜'],['book','📚'],['game','🎮'],['gift','🎁']
]
const iconEmoji=(name?:string|null)=>DEFAULT_ICONS.find(([k])=>k===name)?.[1]||'🛍️'

export default function Categories(){
  const {store}=useStore();const [rows,setRows]=useState<any[]>([]);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false)
  const empty={id:'',name:'',slug:'',icon_type:'default',icon_name:'bag',icon_image_url:'',is_active:true,sort_order:0}
  const [form,setForm]=useState<any>(empty)
  const editing=!!form.id
  async function load(){if(!store)return;const {data,error}=await getBrowserSupabase().from('categories').select('*').eq('store_id',store.id).order('sort_order').order('name');if(error)return alert(error.message);setRows(data||[])}
  useEffect(()=>{load()},[store])
  function set(k:string,v:any){setForm((x:any)=>({...x,[k]:v}))}
  function reset(){setForm(empty)}
  function edit(c:any){setForm({id:c.id,name:c.name||'',slug:c.slug||'',icon_type:c.icon_type||'default',icon_name:c.icon_name||'bag',icon_image_url:c.icon_image_url||'',is_active:c.is_active!==false,sort_order:c.sort_order||0});window.scrollTo({top:0,behavior:'smooth'})}
  async function upload(file:File){if(!store)return;setUploading(true);try{const s=getBrowserSupabase();const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`${store.id}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await s.storage.from('category-icons').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error)throw error;const {data}=s.storage.from('category-icons').getPublicUrl(path);setForm((x:any)=>({...x,icon_type:'upload',icon_image_url:data.publicUrl}))}catch(e:any){alert(e.message)}finally{setUploading(false)}}
  async function submit(e:React.FormEvent){e.preventDefault();if(!store||!form.name.trim())return;setSaving(true);const payload={store_id:store.id,name:form.name.trim(),slug:slugify(form.slug||form.name),icon_type:form.icon_type,icon_name:form.icon_name||'bag',icon_image_url:form.icon_type==='upload'?(form.icon_image_url||null):null,is_active:!!form.is_active,sort_order:Number(form.sort_order||0)};const s=getBrowserSupabase();const result=editing?await s.from('categories').update(payload).eq('id',form.id):await s.from('categories').insert(payload);setSaving(false);if(result.error)return alert(result.error.message);reset();load()}
  async function toggle(c:any){const{error}=await getBrowserSupabase().from('categories').update({is_active:!c.is_active}).eq('id',c.id);if(error)return alert(error.message);load()}
  async function del(id:string){if(!confirm('Hapus kategori? Produk tidak ikut terhapus.'))return;const{error}=await getBrowserSupabase().from('categories').delete().eq('id',id);if(error)return alert(error.message);if(form.id===id)reset();load()}
  const preview=useMemo(()=>form.icon_type==='upload'&&form.icon_image_url?<img src={form.icon_image_url} alt="Preview kategori"/>:<span>{iconEmoji(form.icon_name)}</span>,[form.icon_type,form.icon_image_url,form.icon_name])
  return <div><div className="dashHeader"><div><span className="eyebrow">KATALOG</span><h1>Kategori</h1><p>Setiap kategori bisa pakai ikon bawaan atau upload gambar/icon sendiri.</p></div></div><div className="twoCol categoriesLayout"><section className="panel"><h2>{editing?'Edit Kategori':'Tambah Kategori'}</h2><form onSubmit={submit}><label>Nama<input value={form.name} onChange={e=>{set('name',e.target.value);if(!editing&&!form.slug)set('slug',slugify(e.target.value))}} placeholder="Contoh: Elektronik" required/></label><label>Slug<input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))} placeholder="elektronik"/></label><div className="categoryIconEditor"><div className="categoryIconPreview">{preview}</div><div className="categoryIconFields"><label>Jenis Icon<select value={form.icon_type} onChange={e=>set('icon_type',e.target.value)}><option value="default">Icon Bawaan</option><option value="upload">Upload Gambar/Icon</option></select></label>{form.icon_type==='default'?<label>Pilih Icon<select value={form.icon_name} onChange={e=>set('icon_name',e.target.value)}>{DEFAULT_ICONS.map(([key,emoji])=><option key={key} value={key}>{emoji} {key}</option>)}</select></label>:<><label className="btn ghost categoryUploadBtn">{uploading?'Uploading...':'Upload Icon'}<input hidden type="file" accept="image/*" disabled={uploading} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label><label>atau URL Gambar<input type="url" value={form.icon_image_url||''} onChange={e=>set('icon_image_url',e.target.value)} placeholder="https://.../icon.png"/></label></>}</div></div><div className="formRow"><label>Urutan<input type="number" value={form.sort_order} onChange={e=>set('sort_order',e.target.value)}/></label><label className="check"><input type="checkbox" checked={!!form.is_active} onChange={e=>set('is_active',e.target.checked)}/> Aktif</label></div><div className="categoryFormActions">{editing&&<button type="button" className="btn ghost" onClick={reset}>Batal</button>}<button className="btn primary" disabled={saving}>{saving?'Menyimpan...':editing?'Update Kategori':'Tambah Kategori'}</button></div></form></section><section className="panel"><div className="panelHead"><h2>Daftar Kategori</h2><span>{rows.length} kategori</span></div><div className="catList enhancedCatList">{rows.map(c=><div key={c.id}><div className="catIdentity"><span className="catMiniIcon">{c.icon_type==='upload'&&c.icon_image_url?<img src={c.icon_image_url} alt={c.name}/>:iconEmoji(c.icon_name)}</span><div><b>{c.name}</b><small>/{c.slug}</small></div></div><div className="actions"><button className={c.is_active?'pill success':'pill'} onClick={()=>toggle(c)}>{c.is_active?'Aktif':'Nonaktif'}</button><button onClick={()=>edit(c)}>Edit</button><button onClick={()=>del(c.id)}>Hapus</button></div></div>)}{!rows.length&&<div className="empty">Belum ada kategori.</div>}</div></section></div></div>}
