'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { getBrowserSupabase } from '@/lib/supabase'
import { useStore } from '@/lib/useStore'
import { rupiah } from '@/lib/utils'
export default function Dashboard(){const {store,loading}=useStore();const [stats,setStats]=useState({products:0,published:0,clicks:0,views:0});const [top,setTop]=useState<any[]>([])
useEffect(()=>{if(!store)return;const s=getBrowserSupabase();Promise.all([s.from('products').select('id,is_published,click_count,view_count',{count:'exact'}).eq('store_id',store.id),s.from('products').select('id,name,click_count,price,image_url').eq('store_id',store.id).order('click_count',{ascending:false}).limit(5)]).then(([a,b])=>{const rows=a.data||[];setStats({products:rows.length,published:rows.filter(x=>x.is_published).length,clicks:rows.reduce((n,x)=>n+(x.click_count||0),0),views:rows.reduce((n,x)=>n+(x.view_count||0),0)});setTop(b.data||[])})},[store])
if(loading)return <div className="screenCenter"><div className="spinner"/></div>
return <div><div className="dashHeader"><div><span className="eyebrow">DASHBOARD</span><h1>Halo, {store?.name || 'Affiliator'} 👋</h1><p>Pantau toko affiliate dan produk terbaikmu hari ini.</p></div>{store&&<Link target="_blank" href="/" className="btn primary">Lihat Toko ↗</Link>}</div>
<div className="statGrid"><article><span>Produk</span><strong>{stats.products}</strong><small>{stats.published} dipublish</small></article><article><span>Total Klik</span><strong>{stats.clicks}</strong><small>Ke marketplace</small></article><article><span>Product Views</span><strong>{stats.views}</strong><small>Halaman produk</small></article><article><span>Link Toko</span><strong className="miniText">/</strong><small>Homepage toko</small></article></div>
<div className="twoCol"><section className="panel"><div className="panelHead"><h2>Produk terpopuler</h2><Link href="/dashboard/products">Lihat semua</Link></div>{top.length? <div className="miniList">{top.map((p,i)=><div key={p.id}><span className="rank">{i+1}</span><div className="miniThumb">{p.image_url?<img src={p.image_url} alt=""/>:'✦'}</div><div className="grow"><b>{p.name}</b><small>{rupiah(p.price)}</small></div><strong>{p.click_count} klik</strong></div>)}</div>:<div className="empty">Belum ada produk. <Link href="/dashboard/products/new">Tambah produk pertama</Link>.</div>}</section>
<section className="panel quick"><h2>Mulai cepat</h2><Link href="/dashboard/products/new"><span>＋</span><div><b>Tambah Produk</b><small>Tempel link affiliate dan publish.</small></div></Link><Link href="/dashboard/store"><span>✦</span><div><b>Atur Tampilan</b><small>Logo, banner, warna, dan profil toko.</small></div></Link><Link href="/dashboard/analytics"><span>↗</span><div><b>Lihat Analytics</b><small>Pantau performa klik per produk.</small></div></Link></section></div></div>}
