-- AffiOne v1.0.2 FULL FRESH INSTALL - SINGLE OWNER / SINGLE STORE
-- Jalankan satu kali di Supabase SQL Editor.
-- Setelah itu buat SATU akun owner di Authentication > Users dan nonaktifkan public sign-up.

create extension if not exists pgcrypto;

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'AffiOne Store',
  slug text not null unique default 'main-store',
  tagline text,
  description text,
  logo_url text,
  banner_url text,
  accent_color text not null default '#ff5b66',
  theme text not null default 'soft' check (theme in ('soft','clean','dark')),
  whatsapp text,
  instagram text,
  tiktok text,
  email text,
  seo_title text,
  seo_description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  name text not null,
  slug text not null,
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique(store_id,slug)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  name text not null,
  slug text not null,
  description text,
  image_url text,
  video_url text,
  price numeric(14,2) not null default 0,
  compare_at_price numeric(14,2),
  affiliate_url text not null,
  marketplace text not null default 'Shopee',
  badge text,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  sort_order int not null default 0,
  view_count bigint not null default 0,
  click_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id,slug)
);

create table if not exists public.click_events (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  referrer text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_store on public.products(store_id);
create index if not exists idx_products_pub on public.products(store_id,is_published);
create index if not exists idx_categories_store on public.categories(store_id);
create index if not exists idx_click_events_store_created on public.click_events(store_id,created_at desc);
create index if not exists idx_click_events_product on public.click_events(product_id);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;

drop trigger if exists trg_stores_updated on public.stores;
create trigger trg_stores_updated before update on public.stores for each row execute function public.set_updated_at();
drop trigger if exists trg_products_updated on public.products;
create trigger trg_products_updated before update on public.products for each row execute function public.set_updated_at();

create or replace function public.increment_product_click(p_product_id uuid) returns void language sql security definer set search_path=public as $$
  update public.products set click_count=click_count+1 where id=p_product_id and is_published=true;
$$;
grant execute on function public.increment_product_click(uuid) to anon, authenticated;

create or replace function public.increment_product_view(p_product_id uuid) returns void language sql security definer set search_path=public as $$
  update public.products set view_count=view_count+1 where id=p_product_id and is_published=true;
$$;
grant execute on function public.increment_product_view(uuid) to anon, authenticated;

alter table public.stores enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.click_events enable row level security;

-- Storefront publik hanya membaca toko aktif. Satu owner authenticated mengelola semuanya.
drop policy if exists "stores public read" on public.stores;
create policy "stores public read" on public.stores for select using(is_active=true or auth.role()='authenticated');
drop policy if exists "stores owner update" on public.stores;
create policy "stores owner update" on public.stores for update to authenticated using(true) with check(true);

drop policy if exists "categories public read" on public.categories;
create policy "categories public read" on public.categories for select using(is_active=true or auth.role()='authenticated');
drop policy if exists "categories owner insert" on public.categories;
create policy "categories owner insert" on public.categories for insert to authenticated with check(true);
drop policy if exists "categories owner update" on public.categories;
create policy "categories owner update" on public.categories for update to authenticated using(true) with check(true);
drop policy if exists "categories owner delete" on public.categories;
create policy "categories owner delete" on public.categories for delete to authenticated using(true);

drop policy if exists "products public read" on public.products;
create policy "products public read" on public.products for select using(is_published=true or auth.role()='authenticated');
drop policy if exists "products owner insert" on public.products;
create policy "products owner insert" on public.products for insert to authenticated with check(true);
drop policy if exists "products owner update" on public.products;
create policy "products owner update" on public.products for update to authenticated using(true) with check(true);
drop policy if exists "products owner delete" on public.products;
create policy "products owner delete" on public.products for delete to authenticated using(true);

drop policy if exists "click public insert" on public.click_events;
create policy "click public insert" on public.click_events for insert to anon,authenticated with check(exists(select 1 from public.products p where p.id=product_id and p.store_id=store_id and p.is_published=true));
drop policy if exists "click owner read" on public.click_events;
create policy "click owner read" on public.click_events for select to authenticated using(true);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('product-images','product-images',true,5242880,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update set public=true;

drop policy if exists "product images public read" on storage.objects;
create policy "product images public read" on storage.objects for select using(bucket_id='product-images');
drop policy if exists "product images auth upload" on storage.objects;
create policy "product images auth upload" on storage.objects for insert to authenticated with check(bucket_id='product-images');
drop policy if exists "product images owner update" on storage.objects;
create policy "product images owner update" on storage.objects for update to authenticated using(bucket_id='product-images') with check(bucket_id='product-images');
drop policy if exists "product images owner delete" on storage.objects;
create policy "product images owner delete" on storage.objects for delete to authenticated using(bucket_id='product-images');

-- Tepat satu storefront utama.
insert into public.stores(name,slug,tagline,description,seo_title,seo_description)
select 'AffiOne Store','main-store','Produk pilihan terbaik untuk kamu.','Temukan rekomendasi produk pilihan dan beli langsung melalui marketplace favoritmu.','AffiOne Store — Rekomendasi Produk','Kumpulan produk affiliate pilihan dalam satu toko.'
where not exists (select 1 from public.stores);
